[ card ]
chip_card_number    = "{enter_your_own_chip_card_number_in_config}"
password            = "{enter_your_own_chip_card_password}"

[ server ]
login_url           = "https://potko.ekoplus.si/vs_uporabniki/login"
dashboard_url_base  = "https://potko.ekoplus.si/vs_uporabniki/dashboard"

[ dates ]
date_from           = "01.06.2025"
date_to             = "30.06.2025"

[ output ]
mode                = "default" # default | months | years

[ cost ]
bio                 = 0.1335
mko                 = 2.4809
min_bio             = 1.068
min_mko             = 14.8854

[ logging ]
level               = "INFO"
